In [1]:
import pandas as pd
import numpy as np

## Import your dataset which contain at least 2 tables. And then create NaN value in your dataset for practice.

In [2]:
df = pd.DataFrame({
        "personID":[1010,2020,3030,4040,5050],
        "first": ["John", "Mary","Robbie","Brandon","Charlie"],
        "last": ["Doe", "Bo","Wu","Lee","Petterson"],
        "height": [5.5, 6.0, 7.0, 8.0,5.0],
        "weight": [130, 150, 160, 125, 120],
    })

df

   personID    first       last  height  weight
0      1010     John        Doe     5.5     130
1      2020     Mary         Bo     6.0     150
2      3030   Robbie         Wu     7.0     160
3      4040  Brandon        Lee     8.0     125
4      5050  Charlie  Petterson     5.0     120

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   personID  5 non-null      int64
 1   first     5 non-null      object
 2   last      5 non-null      object
 3   height    5 non-null      float64
 4   weight    5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 328.0+ bytes

In [20]:
np.random.seed(50)
col_name=['height','weight']
mask = np.random.choice([True, False], size=df[col_name].shape)
mask[mask.all(1),-1] = 0
print(mask)
df[col_name]=df[col_name].mask(mask)

df

[[ True False]
 [False False]
 [False  True]
 [ True False]
 [False  True]]

   personID    first       last  height  weight
0      1010     John        Doe     NaN     NaN
1      2020     Mary         Bo     6.0   150.0
2      3030   Robbie         Wu     7.0     NaN
3      4040  Brandon        Lee     NaN     NaN
4      5050  Charlie  Petterson     5.0     NaN

In [21]:
df2 = pd.DataFrame({
        "personID":[1010,2020,3030,4040,5050],
        "salary": [5000, 6500, 6000, 3000,2000],
        "term": ["contract", "permanent", "contract", "contract", "permanent"],
    })


np.random.seed(10)
col_name=['salary','term']
mask = np.random.choice([True, False], size=df2[col_name].shape)
mask[mask.all(1),-1] = 0
print(mask)
df2[col_name]=df2[col_name].mask(mask)
df2

[[False False]
 [ True False]
 [ True False]
 [False  True]
 [False False]]

   personID  salary       term
0      1010  5000.0   contract
1      2020     NaN  permanent
2      3030     NaN   contract
3      4040  3000.0        NaN
4      5050  2000.0  permanent

In [ ]:
df2.isnull().sum()
df2.info()
df2['salary'].fillna(df2['salary'].mean(), inplace=True)
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   personID  5 non-null      int64
 1   salary    3 non-null      float64
 2   term      4 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes

   personID       salary       term
0      1010  5000.000000   contract
1      2020  3333.333333  permanent
2      3030  3333.333333   contract
3      4040  3000.000000        NaN
4      5050  2000.000000  permanent

In [ ]:
df_merge=df.merge(df2, left_on='personID', right_on='personID')
df_merge

   personID    first       last  height  weight       salary       term
0      1010     John        Doe     NaN   130.0  5000.000000   contract
1      2020     Mary         Bo     6.0   150.0  3333.333333  permanent
2      3030   Robbie         Wu     7.0     NaN  3333.333333   contract
3      4040  Brandon        Lee     NaN   125.0  3000.000000        NaN
4      5050  Charlie  Petterson     5.0     NaN  2000.000000  permanent

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   personID  5 non-null      int64
 1   first     5 non-null      object
 2   last      5 non-null      object
 3   height    3 non-null      float64
 4   weight    3 non-null      float64
 5   salary    5 non-null      float64
 6   term      4 non-null      object
dtypes: float64(3), int64(1), object(3)
memory usage: 320.0+ bytes

In [ ]:
df.melt()

   variable  value
0         A    1.0
1         A    2.0
2         A    3.0
3         B    NaN
4         B    5.0
5         B    NaN
6         C    7.0
7         C    NaN
8         C    NaN
9         D   10.0
10        D    NaN
11        D   12.0

## Your task

* Inspect a dataframe with `df.head()`, `df.tail()`, `df.info()`, `df.describe()`.
* Show how many missing values in your data, each column.
* Manipulate how a dataframe displays in Jupyter by modifying Pandas configuration options such as `pd.set_option("display.max_rows", n)`.
* Rename columns of a dataframe using the `df.rename()` function or by accessing the `df.columns` attribute.
* Modify the index name and index values of a dataframe using `.set_index()`, `.reset_index()` , `df.index.name`, `.index`.
* Use `df.melt()` and `df.pivot()` to reshape dataframes, specifically to make tidy dataframes.
* Combine dataframes using `df.merge()` and `pd.concat()` and know when to use these different methods.
* Apply functions to a dataframe `df.apply()` and `df.applymap()`
* Find the data which satisfy specific condition using `df.query()`
* Perform grouping and aggregating operations using `df.groupby()` and `df.agg()`.
* Perform aggregating methods on grouped or ungrouped objects such as finding the minimum, maximum and sum of values in a dataframe using `df.agg()`.
* Remove or fill missing values in a dataframe with `df.dropna()` and `df.fillna()` please practice using different method of filling missing value.
* Practice imputing missing values using the `SimpleImputer` Class in `sklearn`

## For extra miles:


1.   clean your text data using regex function
2.   clean the text and nested json in https://raw.githubusercontent.com/nnqomariyah/Fundamentals_of_Data_Science/main/week_3/data/movies_metadata.csv